bowlingapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import bowling_home, core, each_game_data, finish, game, member, login

urlpatterns = [
    path('admin/', admin.site.urls), 

    path('home/', bowling_home.BowlingHome.as_view(), name='home'),

    path('game_list/', each_game_data.EachGameDataList.as_view(), name='game_list'),
    path('game_detail/<int:pk>/',each_game_data. gamedetailview, name='game_detail'),
    path('game_delete/<int:pk>/', each_game_data.EachGameDataDelete.as_view(), name='game_delete'),
    path('game_update/<int:pk>/', each_game_data.EachGameDataUpdate.as_view(), name='game_update'),

    path('member_list/', member.memberlistview, name='member_list'),
    path('member_add/', member.MemberCreate.as_view(), name='member_add'),
    path('member_detail/<int:pk>/', member.MemberDetail.as_view(), name='member_detail'),
    path('member_update/<int:pk>/', member.MemberUpdate.as_view(), name='member_update'),
    path('member_delete/<int:pk>/', member.MemberDelete.as_view(), name='member_delete'),

    path('core_detale_1/<int:pk>/', game.GameDetail.as_view(), name='core_detail_1'),
    path('core_delete_1/<int:pk>/', game.GameDelete.as_view(), name='core_delete_1'),

    path('core_detale_2/<int:pk>/', core.CoreDetail.as_view(), name='core_detail_2'),
    path('core_delete_2/<int:pk>/', core.CoreDelete.as_view(), name='core_delete_2'),
    path('core_update/<int:pk>/', core.CoreDetail.as_view(), name='core_update'),
    path('index/', core.coreview, name="index"),

    path('game_finish/', finish.finishview, name="game_finish"),

    path('signup/', login.signupview, name="signup"),
    path('login/', login.loginview, name="login"),
    path('logout/', login.logoutview, name="logout"),

]

bowlingproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bowlingapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bowlingapp/models.py
from django.contrib.auth import default_app_config
from django.db import models

class MemberModel(models.Model):
    membername = models.CharField(max_length=10)
    point_total = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.membername

class GameModel(models.Model):
    membername = models.CharField(max_length=10)
    point_total = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.membername

class TeamCalculusModel(models.Model):
    team = models.CharField(max_length=3, default=0)
    raund = models.IntegerField(default=0)
    sum_total = models.IntegerField(default=0)
    point_alloc = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.team + ', SUM ' + str(self.sum_total) + ', Point ' + str(self.point_alloc)

class CoreModel(models.Model):
    teams = (('A', 'A'),('B', 'B'),('C', 'C'),)
    member = models.CharField(max_length=10, default=0)
    raund = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    team_choice = models.CharField(max_length=1, choices=teams)
    pin = models.IntegerField(default=0)
    handicap = models.CharField(default=0, max_length=5)
    score_h = models.IntegerField(default=0)
    point = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.member + ', R' + str(self.raund) + ', Score ' + str(self.score)

class EachGameDataModel(models.Model):
    datetime = models.CharField(max_length=20)
    members = models.TextField(max_length=100)
    points = models.TextField(max_length=100)
    aves = models.TextField(max_length=100)
    maxs = models.TextField(max_length=100)
    mins = models.TextField(max_length=100)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.datetime

bowlingapp/forms.py
from django import forms
from django.shortcuts import render
from django.forms import widgets
from .models import CoreModel, MemberModel

class SpendingForm(forms.Form):
    member_list = forms.ModelChoiceField(
        label="Member",
        queryset=MemberModel.objects.all(),
        widget=forms.RadioSelect,
        empty_label=None,
    )
    class Meta:
        teams = (('A','A'),('B','B'),('C','C'))
        model = CoreModel
        fields = ('member_list', 'raund', 'score', 'point_alloc', 'team_choice','pin', 'handicap')
        widgets = {
            'raund': forms.IntegerField(),
            'score': forms.IntegerField(),
            'team_choice': forms.CharField(),
            'pin': forms.IntegerField(),
            'handicap' : forms.CharField(),
        }
    

    
    

bowlingapp/views/core.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.timezone import localtime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Avg, Max, Min
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from ..models import CoreModel, MemberModel, GameModel, CoreModel, TeamCalculusModel, EachGameDataModel
from ..forms import SpendingForm

class CoreDetail(DetailView, LoginRequiredMixin):
    template_name = 'core_detail_2.html'
    model = CoreModel

class CoreDelete(DeleteView, LoginRequiredMixin):
    template_name = 'core_delete_2.html'
    model = CoreModel
    success_url = reverse_lazy('index')

@login_required
def coreview(request):
    today = str(timezone.now()).split('-')
    member_list = MemberModel.objects.filter(user_set=request.user)
    core = CoreModel.objects.filter(user_set=request.user).order_by('-raund', 'member')
    game = GameModel.objects.filter(user_set=request.user).order_by('membername')
    calucu = TeamCalculusModel.objects.filter(user_set=request.user).order_by('-raund')
    form = SpendingForm()    #フォームを読み込む
    context = {
            'year' : today[0],
            'month' : today[1],
            'member_list' : member_list,
            'core' : core,
            'game' : game,
            'calucu' : calucu,
            'form' : form,
            }

    if request.method == 'POST':    # フォームでデータが送られてきたら
        if 'ok' in request.POST:
            data = request.POST         # 以下フォームのデータの代入
            member_name = data['member_list']
            raund = data['raund']
            score = data['score']
            team_choice = data['team_choice']
            pin = data['pin']
            hand = data['handicap']
            
            if int(raund) <= 0:
                return redirect(to='/index/')

            if int(score) >= 0: # 0 or +スコアなら通常通り
                aave = int(score)
                bmax = int(score)
                cmin = int(score)
                count = 1
            elif int(score) < 0: # -スコアならpostしたスコア無視 >>> 単純な更新！！
                aave = 0
                bmax = 0
                cmin = 10000
                count = 0
            # Average計算
            for m in CoreModel.objects.filter(user_set=request.user, member=member_name).annotate(avg_score=Max('score')):
                aave += int('{}'.format(m.avg_score))
                count += 1
            if count != 0:
                aave //= count
            # Max計算
            for m in CoreModel.objects.filter(user_set=request.user, member=member_name).annotate(max_score=Max('score')):
                b = int('{}'.format(m.max_score))
                if b > bmax:
                    bmax = b
            # Min計算
            for m in CoreModel.objects.filter(user_set=request.user, member=member_name).annotate(min_score=Min('score')):
                c = int('{}'.format(m.min_score))
                if c < cmin:
                    cmin = c

            # ハンデありのスコア計算
            if hand[0] == '+':
                score_h = int(score) + int(hand[1:])
            elif hand[0] == 'x':
                score_h = int(score) * float(hand[1:])
            
            if int(score) >= 0:
                CoreModel.objects.create(    # データベースにデータを入れる
                    member = str(member_name),
                    raund = int(raund),
                    score = int(score),
                    ave = int(aave),
                    max = int(bmax),
                    min = int(cmin),
                    team_choice = str(team_choice),
                    pin = int(pin),
                    handicap = str(hand),
                    score_h = int(score_h),
                    user_set = str(request.user),
                )   
            #---------------------------------------------------
            # CoreModelのデータベースに依存させたい
            GameModel.objects.filter(user_set=request.user, membername=member_name).delete() # 同じ名前のデータを削除、最新のみにするため
            if count != 0:                                       # count=0 >>> 保存するデータ無し
                GameModel.objects.create(                        # データベースにデータを入れる
                    membername = str(member_name),
                    ave = int(aave),
                    max = int(bmax),
                    min = int(cmin),
                    user_set = str(request.user),
                )   
            
            # pointの計算------------------------------------------ CoreModelのデータベースに依存させたい
            #-----------------------------------------------------
            sc_a = sc_b = sc_c = point_a = point_b = point_c = 0
            for m in CoreModel.objects.filter(user_set=request.user, team_choice="A", raund=raund).annotate(score_cul=Max('score_h')): # 保存してあるスコア(ハンデ込み)を取り出して合計出す
                sc_a += int('{}'.format(m.score_cul)) 
            for m in CoreModel.objects.filter(user_set=request.user, team_choice="B", raund=raund).annotate(score_cul=Max('score_h')):
                sc_b += int('{}'.format(m.score_cul))
            for m in CoreModel.objects.filter(user_set=request.user, team_choice="C", raund=raund).annotate(score_cul=Max('score_h')):
                sc_c += int('{}'.format(m.score_cul))
            
            if sc_a > sc_b and sc_c == 0:              # 2チーム対戦
                point_a = sc_a - sc_b
                point_b = sc_b - sc_a
            elif sc_a < sc_b and sc_c == 0:
                point_a = sc_a - sc_b
                point_b = sc_b - sc_a
            elif sc_a == sc_b and sc_c == 0:
                point_a = point_b = point_c = 0
            elif sc_a > sc_b and sc_a > sc_c:          # 3チーム対戦
                if sc_b > sc_c:              
                    point_a = sc_a - sc_c
                    point_c = sc_c - sc_a
                elif sc_b < sc_c:
                    point_a = sc_a - sc_b
                    point_b = sc_b - sc_a
                elif sc_b == sc_c:               # 下位同点
                    point_a = sc_a - sc_b
                    point_b = point_c = -(point_a // 2)
            elif sc_b > sc_a and sc_b > sc_c:  
                if sc_a > sc_c:
                    point_b = sc_b - sc_c
                    point_c = sc_c - sc_b
                elif sc_a < sc_c:
                    point_b = sc_b - sc_a
                    point_a = sc_a - sc_b
                elif sc_a == sc_c:
                    point_b = sc_b - sc_a
                    point_a = point_c = -(point_b // 2)
            elif sc_c > sc_a and sc_c > sc_b: 
                if sc_a > sc_b:
                    point_c = sc_c - sc_b
                    point_b = sc_b - sc_c
                elif sc_a < sc_b:
                    point_c = sc_c - sc_a
                    point_a = sc_a - sc_c
                elif sc_a == sc_b:
                    point_c = sc_c - sc_a
                    point_a = point_b = -(point_c // 2)
            elif sc_a == sc_b and sc_a > sc_c:   # 上位同点
                point_a = point_b = (sc_a - sc_c) // 2
                point_c = sc_c - sc_a
            elif sc_a == sc_c and sc_a > sc_b:  
                point_a = point_c = (sc_a - sc_b) // 2
                point_b = sc_b - sc_a
            elif sc_b == sc_c and sc_b > sc_a:  
                point_b = point_c = (sc_b - sc_a) // 2
                point_a = sc_a - sc_b
            
            if int(score) >= 0:
                TeamCalculusModel.objects.filter(user_set=request.user, raund=raund).delete() # 最新だけ残すため
                TeamCalculusModel.objects.create(                      # 最新情報のみ、データベースにデータを入れる
                    team = "A",
                    raund = int(raund),
                    sum_total = sc_a,
                    point_alloc = int(point_a) * int(pin),
                    user_set = str(request.user),
                )   
                TeamCalculusModel.objects.create(   
                    team = "B",
                    raund = int(raund),
                    sum_total = sc_b,
                    point_alloc = int(point_b) * int(pin),
                    user_set = str(request.user),
                )   
                TeamCalculusModel.objects.create(   
                    team = "C",
                    raund = int(raund),
                    sum_total = sc_c,
                    point_alloc = int(point_c) * int(pin),
                    user_set = str(request.user),
                )   
            for m in TeamCalculusModel.objects.filter(user_set=request.user, raund=raund, team='A').annotate(pt=Max('point_alloc')): 
                pa = int('{}'.format(m.pt)) 
                CoreModel.objects.filter(user_set=request.user, raund=raund, team_choice='A').update(point=pa)
            for m in TeamCalculusModel.objects.filter(user_set=request.user, raund=raund, team='B').annotate(pt=Max('point_alloc')):
                pb = int('{}'.format(m.pt))
                CoreModel.objects.filter(user_set=request.user, raund=raund, team_choice='B').update(point=pb)
            for m in TeamCalculusModel.objects.filter(user_set=request.user, raund=raund, team='C').annotate(pt=Max('point_alloc')):
                pc = int('{}'.format(m.pt))
                CoreModel.objects.filter(user_set=request.user, raund=raund, team_choice='C').update(point=pc)

            gpt = 0
            for g in GameModel.objects.filter(user_set=request.user).annotate(mn=Max('membername')):
                g = '{}'.format(g.mn)
                for n in CoreModel.objects.filter(user_set=request.user, member=g).annotate(pt=Max('point')):
                    gpt += int('{}'.format(n.pt))
                GameModel.objects.filter(user_set=request.user, membername=g).update(point_total=gpt)

templates/core/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">GAME</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link" href="{% url 'game_finish' %}">-Finish-</a>
    </nav>
    </div>
</header>
<body>
    <nav role="navigation">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul id="menu">
                <ul id="accordion" class="accordion">
                    <li>
                        <div class="link"><i class="fa fa-paint-brush"></i>Member Data<i class="fa fa-chevron-down"></i></div>
                        <ul class="submenu">
                            <li>
                                <table>
                                    <tr>
                                        <th>MEMBER</th>
                                        <th>POINT</th>
                                        <th>AVE</th>
                                        <th>MAX</th>
                                        <th>MIN</th>
                                    </tr>
                                    {% for g in game %}
                                    {% ifequal g.user_set user.get_username %}
                                    <tr>
                                        <th><a href="{% url 'core_detail_1' g.pk %}" class="btn btn-gradient btn-border-gradient" style="padding:0.5px 3px; margin:0.5px 1px; color: #b63b4d;">{{ g.membername }}</a></th>
                                        <th>{{ g.point_total }}</th>
                                        <th>{{ g.ave }}</th>
                                        <th>{{ g.max }}</th>
                                        <th>{{ g.min }}</th>
                                    </tr>
                                    {% endifequal %}
                                    {% endfor %}
                                </table>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <div class="link"><i class="fa fa-code"></i>Raund Data<i class="fa fa-chevron-down"></i></div>
                        <ul class="submenu">
                          <li>
                            <table>
                                <tr>
                                    <th>Member</th>
                                    <th>Raund</th>
                                    <th>Score</th>
                                    <th>hcp</th>
                                    <th>Point</th>
                                    <th>Team</th>
                                </tr>
                                {% for m in core %}
                                {% ifequal m.user_set user.get_username %}
                                <tr>
                                    <td>{{ m.member}}</td>
                                    <td>R{{ m.raund }}</td>
                                    <td>{{ m.score}}</td>
                                    <td>{{ m.handicap }}</td>
                                    <td>{{ m.point }}</td>
                                    <td><a href="{% url 'core_detail_2' m.pk %}" class="btn btn-gradient btn-border-gradient" style="padding:0.5px 3px; margin:0.5px 1px; color: #b63b4d;">{{ m.team_choice }}</a></td>
                                </tr>
                                {% endifequal %}
                                {% endfor %}
                            </table>
                          </li>
                        </ul>
                    </li>
                    <li>
                        <div class="link"><i class="fa fa-code"></i>Team Data<i class="fa fa-chevron-down"></i></div>
                        <ul class="submenu">
                            <li>
                                <table>
                                    <tr>
                                        <th>Team</th>
                                        <th>Raund</th>
                                        <th>Total Score</th>
                                        <th>Point</th>
                                    </tr>
                                    {% for m in calucu %}
                                    {% ifequal m.user_set user.get_username %}
                                    <tr>
                                        <td>{{ m.team }}</td>
                                        <td>R{{ m.raund }}</td>
                                        <td>{{ m.sum_total }}</td>
                                        <td>{{ m.point_alloc }}</td>
                                    </tr>
                                    {% endifequal %}
                                    {% endfor %}
                                </table>
                            </li>
                        </ul>
                    </li>
                </ul>
            </ul>
        </div>
    </nav>
    <!--h5>{{ year }}年{{ month }}月</h5-->
    <form action="/index/" method="post"> {% csrf_token %}
        <p><label class="forms" for="id_member_list" style="width:70px; text-align: left;">Name</label>
            <select type="radio" name="member_list" required id="id_member_list">
                {% for mem in member_list %}
                <option name="member_list" value="{{ mem.membername }}" checked>{{ mem.membername }}</option>
                {% endfor %}
            </select>
        </p>
        <p><label class="forms" for="id_raund" style="width:70px; text-align: left;">Raund</label><input type="number" name="raund" required id="id_raund"></p>
        <p><label class="forms" for="id_score" style="width:70px; text-align: left;">Score</label><input type="number" name="score" required id="id_score"></p>
        <p><label class="forms" for="id_pin" style="width:70px; text-align: left;">Pin</label><input type="number" name="pin" required id="id_pin"></p>
        <p><label class="forms" for="id_handicap" style="width:70px; text-align: left;">Handicap</label>
            <select type="char" name="handicap" id="id_handicap" required>
                <option name="handicap" value="+0">0</option>
                <option name="handicap" value="+10">+10</option>
                <option name="handicap" value="+20">+20</option>
                <option name="handicap" value="+30">+30</option>
                <option name="handicap" value="+40">+40</option>
                <option name="handicap" value="+50">+50</option>
                <option name="handicap" value="x1.1">x1.1</option>
                <option name="handicap" value="x1.2">x1.2</option>
                <option name="handicap" value="x1.3">x1.3</option>
                <option name="handicap" value="x1.4">x1.4</option>
                <option name="handicap" value="x1.5">x1.5</option>
            </select>
        </p>
        <p style="margin-bottom: 0;"><label class="forms" for="id_team_choice" style="width:70px; text-align: left;">Team</label>
            <select type="char" name="team_choice" id="id_team_choice" required>
                <option name="team_choice" value="" disabled>------</option>
                <option name="team_choice" value="A">A</option>
                <option name="team_choice" value="B">B</option>
                <option name="team_choice" value="C">C</option>
            </select>
            <br><span style="font-size: 9px; text-align: right;">　　　　* Use A and B for 2 teams</span>
        </p>
        <input class="button" type="submit" name="ok" value="OK">
        <!--input type="submit" name="button_1" value="ボタン1"--> 
    </form>


    <!-- モーダルエリアここから 
    <section id="modalArea" class="modalArea">
        <div id="modalBg" class="modalBg"></div>
        <div class="modalWrapper">
        <div class="modalContents">
            <h1>Do you really want to finish?</h1>
            <p>
                <button class="orbtn" id="modalYesBtn">YES</button>
            </p>
        </div>
        <div id="closeModal" class="closeModal">
            ×
        </div>
        </div>
    </section>
     モーダルエリアここまで -->


</body>       
<p></p>
{% endblock content %}