bowlingapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import bowling_home, core, each_game_data, finish, game, member, login

urlpatterns = [
    path('admin/', admin.site.urls), 

    path('home/', bowling_home.BowlingHome.as_view(), name='home'),

    path('game_list/', each_game_data.EachGameDataList.as_view(), name='game_list'),
    path('game_detail/<int:pk>/',each_game_data. gamedetailview, name='game_detail'),
    path('game_delete/<int:pk>/', each_game_data.EachGameDataDelete.as_view(), name='game_delete'),
    path('game_update/<int:pk>/', each_game_data.EachGameDataUpdate.as_view(), name='game_update'),

    path('member_list/', member.memberlistview, name='member_list'),
    path('member_add/', member.MemberCreate.as_view(), name='member_add'),
    path('member_detail/<int:pk>/', member.MemberDetail.as_view(), name='member_detail'),
    path('member_update/<int:pk>/', member.MemberUpdate.as_view(), name='member_update'),
    path('member_delete/<int:pk>/', member.MemberDelete.as_view(), name='member_delete'),

    path('core_detale_1/<int:pk>/', game.GameDetail.as_view(), name='core_detail_1'),
    path('core_delete_1/<int:pk>/', game.GameDelete.as_view(), name='core_delete_1'),

    path('core_detale_2/<int:pk>/', core.CoreDetail.as_view(), name='core_detail_2'),
    path('core_delete_2/<int:pk>/', core.CoreDelete.as_view(), name='core_delete_2'),
    path('core_update/<int:pk>/', core.CoreDetail.as_view(), name='core_update'),
    path('index/', core.coreview, name="index"),

    path('game_finish/', finish.finishview, name="game_finish"),

    path('signup/', login.signupview, name="signup"),
    path('login/', login.loginview, name="login"),
    path('logout/', login.logoutview, name="logout"),

]

bowlingproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bowlingapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bowlingapp/models.py
from django.contrib.auth import default_app_config
from django.db import models

class MemberModel(models.Model):
    membername = models.CharField(max_length=10)
    point_total = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.membername

class GameModel(models.Model):
    membername = models.CharField(max_length=10)
    point_total = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.membername

class TeamCalculusModel(models.Model):
    team = models.CharField(max_length=3, default=0)
    raund = models.IntegerField(default=0)
    sum_total = models.IntegerField(default=0)
    point_alloc = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.team + ', SUM ' + str(self.sum_total) + ', Point ' + str(self.point_alloc)

class CoreModel(models.Model):
    teams = (('A', 'A'),('B', 'B'),('C', 'C'),)
    member = models.CharField(max_length=10, default=0)
    raund = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    ave = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    team_choice = models.CharField(max_length=1, choices=teams)
    pin = models.IntegerField(default=0)
    handicap = models.CharField(default=0, max_length=5)
    score_h = models.IntegerField(default=0)
    point = models.IntegerField(default=0)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.member + ', R' + str(self.raund) + ', Score ' + str(self.score)

class EachGameDataModel(models.Model):
    datetime = models.CharField(max_length=20)
    members = models.TextField(max_length=100)
    points = models.TextField(max_length=100)
    aves = models.TextField(max_length=100)
    maxs = models.TextField(max_length=100)
    mins = models.TextField(max_length=100)
    user_set = models.CharField(max_length=20, default=0)
    def __str__(self):
        return self.datetime

bowlingapp/views/login.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.timezone import localtime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Avg, Max, Min
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from ..models import CoreModel, MemberModel, GameModel, CoreModel, TeamCalculusModel, EachGameDataModel
from ..forms import SpendingForm

def signupview(request):
    if request.method == 'POST':
        username_data = request.POST['username_data']
        password_data = request.POST['password_data']
        try:
            User.objects.create_user(username_data, '', password_data)
        except IntegrityError:
            return render(request, 'signup.html', {'error': 'このユーザーは既に登録されています。'})
    else:
        return render(request, 'signup.html', {})
    return render(request, 'signup.html', {})

def loginview(request):
    if request.method == 'POST':
        username_data = request.POST['username_data']
        password_data = request.POST['password_data']
        user = authenticate(request, username=username_data, password=password_data)
        if user is not None:
            login(request, user)
            return redirect('home') # 成功 >>> url homeに遷移
        else:
            return redirect('login') # 失敗 >>> url login繰り返し
    return render(request, 'login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')
    return render(request, 'logout.html')

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <title>BowlingApp</title>
    
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.79.0">
    
        <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <!--JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
    
    
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }
    
            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                font-size: 3.5rem;
                }
            }
        </style>
        
        <!-- Custom styles for this template -->
        {% load static %}
        <link href="{% static 'cover.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'accordion.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'modal.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'menutoggle.css' %}" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="{% static 'accordion.js' %}"></script>
        {% block header %}
        {% endblock header %}   
    </head>
    <body class="d-flex h-100 text-center text-white bg-dark">   
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            {% block content %}
            {% endblock content %}
            <footer class="mt-auto text-white-50">
                {% if user.is_authenticated %}
                <p style="font-size: small; margin-bottom: 0;">login user "{{ user.get_username }}"</p>
                {% else %}
                <p style="font-size: small; margin-bottom: 0;">You are not logged in</p>
                <p style="font-size: small; margin-bottom: 0;">Please login</p>
                {% endif %}
                {% block footer %}
                {% endblock footer %}
                <p style="font-size: small;">&copy; 2021 mappy</p>
            </footer> 
        </div>   
    </body>
</html>

templates/core_delete_1.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <h3 class="float-md-start mb-0">GAME</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">DELETE</a>
        <a class="nav-link" aria-current="page" href="{% url 'index' %}">back</a>
    </nav>
</header>
<form action="" method="POST">{% csrf_token %}
    <p>Do you really want to 'delete' ?</p>
    <input class="button" type="submit" value="DELETE">
</form>
{% endblock content %}

templates/core_detail_1.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="mb-auto">
    <h3 class="float-md-start mb-0">GAME</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'index' %}">back</a>
        <a class="nav-link active" aria-current="page" href="#">DETAIL</a>
        <!--a class="nav-link" href="{% url 'core_update' object.pk %}">update</a-->
        <a class="nav-link" href="{% url 'core_delete_1' object.pk %}">delete</a>
    </nav>
</header>
<body>
    <table>
        <tr>
            <td style="width:50%"> Member </td>
            <td> {{ object.membername }} </td>
        </tr>
        <tr>
            <td>Point</td>
            <td>{{ object.point_total }}</td>
        </tr>
        <tr>
            <td>Average</td>
            <td>{{ object.ave }}</td>
        </tr>
        <tr>
            <td>Max</td>
            <td>{{ object.max }}</td>
        </tr>
        <tr>
            <td>Min</td>
            <td>{{ object.min }}</td>
        </tr>
    </table>
</body>
{% endblock content %}

templates/core_detail_2.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="mb-auto">
    <h3 class="float-md-start mb-0">GAME</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'index' %}">back</a>
        <a class="nav-link active" aria-current="page" href="#">DETAIL</a>
        <!--a class="nav-link" href="{% url 'core_update' object.pk %}">update</a-->
        <a class="nav-link" href="{% url 'core_delete_2' object.pk %}">delete</a>
    </nav>
</header>
<body>
    <table>
        <tr>
            <td style="width:50%"> Member </td>
            <td> {{ object.member }} </td>
        </tr>
        <tr>
            <td>Raund</td>
            <td>{{ object.raund }}</td>
        </tr>
        <tr>
            <td>Score</td>
            <td>{{ object.score }}</td>
        </tr>
        <tr>
            <td>Average</td>
            <td>{{ object.ave }}</td>
        </tr>
        <tr>
            <td>Max</td>
            <td>{{ object.max }}</td>
        </tr>
        <tr>
            <td>Min</td>
            <td>{{ object.min }}</td>
        </tr>
        <tr>
            <td>Team</td>
            <td>{{ object.team_choice }}</td>
        </tr>
    </table>
</body>
{% endblock content %}

templates/game_delete.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">GAME DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="#">DELETE</a>
        <a class="nav-link" href="{% url 'game_detail' object.pk %}">back</a>
    </nav>
    </div>
</header>
<form action="" method="POST">{% csrf_token %}
    <p>Do you really want to 'delete' ?</p>
    <input class="button" type="submit" value="DELETE">
</form>
{% endblock content %}

templates/game_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">GAME DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="#">DETAIL</a>
        <a class="nav-link" href="{% url 'game_list' %}">back</a>
    </nav>
    </div>
</header>
<div class='container'>
    <div class="card">
        <h5 class="card-header">{{object.datetime}}</h5>
        <div class="card-body">
            <div class="items">
                <div class="item" style="width:35%;">
                    <p class="item">Member</p>
                    {% for m in member_list %}
                    <p>{{ m }}</p>
                    {% endfor %}
                </div>
                <div class="item" style="width:20%;">
                    <p class="item">Point</p>
                    {% for m in member_point %}
                    <p>{{ m }}</p>
                    {% endfor %}
                </div>
                <div class="item" style="width:15%;">
                    <p class="item">Ave</p>
                    {% for m in member_ave %}
                    <p>{{ m }}</p>
                    {% endfor %}
                </div>
                <div class="item" style="width:15%;">
                    <p class="item">Max</p>
                    {% for m in member_max %}
                    <p>{{ m }}</p>
                    {% endfor %}
                </div>
                <div class="item" style="width:15%;">
                    <p class="item">Min</p>
                    {% for m in member_min %}
                    <p>{{ m }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'game_update' object.pk %}" class="btn btn-gradient btn-border-gradient">UPDATE</a>
            <a href="{% url 'game_delete' object.pk %}" class="btn btn-gradient btn-border-gradient">DELETE</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/game_finish.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">GAME</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="＃">FINISH</a>
        <a class="nav-link" href="{% url 'index' %}">back</a>
    </nav>
    </div>
</header>
<form action="" method="POST">{% csrf_token %}
    <p>Do you really want to finish?</p>
    <input class="button" type="submit" value="FINISH">
</form>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<link href="https://fonts.googleapis.com/css?family=Corben:700" rel="stylesheet">
<header class="mb" style="margin-bottom: 40px;">
    <div>
    <h5 class="float-md-start mb-0">HOME</h5>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link home-active" href="{% url 'game_list' %}">&nbsp;game data&nbsp;</a>
        <a class="nav-link home-active" href="{% url 'member_list' %}">member data</a>
    </nav>
    </div>
</header>
<main class="px-3">
    <h1 class="mb title">BowlingAPP</h1>
    <p class="lead">
        <div class="btn-border-gradient-wrap">
            <p><a href="{% url 'index' %}" class="btn btn--circle btn--shadow btn-gradient btn-border-gradient" style="font-size: 25px;">START</a></p>
        </div>
    </p>
</main> 
{% endblock content %}

{% block footer %}
    {% if user.is_authenticated %}
    <a class="nav-link logout" href="{% url 'logout' %}" >logout</a>
    {% else %}
    <a class="nav-link logout" href="{% url 'login' %}" >login</a>
    {% endif %}
{% endblock footer %}

templates/login.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <h6 class="mb title">BowlingAPP</h6>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link home-active" href="{% url 'signup' %}" style="color: #8fc31f;">SIGN UP</a>
    </nav>
</header>
<form class="form-signin" method='post'>{% csrf_token %}
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal" style="color: #88b5c5d9;">Please login</h1>
    <label for="inputEmail" class="visually-hidden">Username</label>
    <input type="text" id="inputEmail" class="form-control" placeholder="username" name="username_data" required autofocus>
    <label for="inputPassword" class="visually-hidden">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="password" name="password_data" required>
    <div class="checkbox mb-3">
    </div>
    <button class="btn btn-gradient btn-border-gradient w-100" type="submit" style="font-weight:bold;">Login</button>
</form>
{% endblock content %}

templates/member_add.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="">
    <div>
    <h3 class="float-md-start mb-0">MEMBER DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="#">ADD</a>
        <a class="nav-link" href="{% url 'member_list' %}">back</a>
    </nav>
    </div>
</header>
<form action="" method="POST">{% csrf_token %}
    <p><label for="id_membername">Membername:</label> <input type="text" name="membername" maxlength="10" required id="id_membername"></p>
    <label for="id_user_set"></label> <input type="hidden" name="user_set" value="{{ request.user }}" maxlength="20" required id="id_user_set">
    <input class="button" type="submit" value="CREATE">
</form>
{% endblock content %}

templates/member_delete.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">MEMBER DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="">DELETE</a>
        <a class="nav-link" href="{% url 'member_detail' object.pk %}">back</a>
    </nav>
    </div>
</header>
<form action="" method="POST">{% csrf_token %}
    <p>Do you really want to 'delete' ?</p>
    <input class="button" type="submit" value="DELETE">
</form>
{% endblock content %}

templates/member_list.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="mb-3">
    <div>
    <h3 class="float-md-start mb-0">MEMBER DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="#">LIST</a>
        <a class="nav-link" href="{% url 'member_add' %}">Add</a>
    </nav>
    </div>
</header>
<nav role="navigation">
    <div id="menuToggle">
        <input type="checkbox" />
        <span></span>
        <span></span>
        <span></span>
        <ul id="menu">
            <div class="container">
                <form action="/member_list/" method="POST">{% csrf_token %}
                    <button class="sort" type="submit" name="high_point" value="high point order">high point order
                    <button class="sort" type="submit" name="high_average" value="high average order">high average order
                    <button class="sort" type="submit" name="high_max" value="high max order">high max order
                    <button class="sort" type="submit" name="high_min" value="high min order">high min order
                </form>
            </div>
        </ul>
    </div>
</nav>
<div class='container' style="margin-top:45px;">
    {% for item in object %}
    {% ifequal item.user_set user.get_username %}
    <div class="card">
        <div class="card-header" style="padding:0;">
            <a href="{% url 'member_detail' item.pk %}" class="btn btn-gradient btn-border-gradient" style="width:100%;">{{ item.membername }}</a>
        </div>
        <div class="card-body" style="padding:0; ">
            <table style="width:100%; font-size:10px;">
                <tr>
                    <td>Point</td>
                    <td>Ave</td>
                    <td>Max</td>
                    <td>Min</td>
                </tr>
                <tr>
                    <td>{{ item.point_total }}</td>
                    <td>{{ item.ave }}</td>
                    <td>{{ item.max }}</td>
                    <td>{{ item.min }}</td>
                </tr>
            </table>
        </div>
    </div>
    {% endifequal %}
    {% endfor %}
</div>
<p></p>
<p></p>
{% endblock content %}

templates/member_update.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <div>
    <h3 class="float-md-start mb-0">MEMBRE DATA</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'home' %}">home</a>
        <a class="nav-link active" href="#">UPDATE</a>
        <a class="nav-link" href="{% url 'member_detail' object.pk %}">back</a>
    </nav>
    </div>
</header>
<form action="" method="POST">{% csrf_token %}
    <p><label for="id_membername" style="width:100px; text-align: left;">Membername</label> <input type="text" name="membername" value="{{ object.membername }}" maxlength="10" id="id_membername" required></p>
    <p><label for="id_point_total" style="width:100px; text-align: left;">Point total</label> <input type="number" name="point_total" value="{{ object.point_total }}" id="id_point_total" required></p>
    <p><label for="id_ave" style="width:100px; text-align: left;">Ave</label> <input type="number" name="ave" value="{{ object.ave }}" id="id_ave" required></p>
    <p><label for="id_max" style="width:100px; text-align: left;">Max</label> <input type="number" name="max" value="{{ object.max }}" id="id_max" required></p>
    <p><label for="id_min"style="width:100px; text-align: left;">Min</label> <input type="number" name="min" value="{{ object.min }}" id="id_min" required></p>
    <input class="button" type="submit" value="UPDATE">
</form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block header %}
{% endblock header %}

{% block content %}
<header class="hd">
    <h6 class="mb title">BowlingAPP</h6>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link home-active" href="{% url 'login' %}" style="color: #8fc31f;">LOGIN</a>
    </nav>
</header>
<form class="form-signin" method='post'>{% csrf_token %}
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal" style="color: #88b5c5d9;">Please sign up</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="inputEmail" class="visually-hidden">Username</label>
    <input type="text" id="inputEmail" class="form-control" placeholder="username" name="username_data" required autofocus>
    <label for="inputPassword" class="visually-hidden">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="password" name="password_data" required>
    <div class="checkbox mb-3">
    </div>
    <button class="btn btn-gradient btn-border-gradient w-100" type="submit" style="font-weight:bold;">Sign up</button>
</form>
{% endblock content %}